### single request
GET http://localhost:8080/api/demo/single

### multiple request
GET http://localhost:8080/api/demo/multiple

### "Transfer-Encoding: chunked" 테스트
GET http://localhost/api/external/messages
#Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
#Accept-Encoding: gzip, deflate, br