version: "3.3"
services:
  demo-api:
    image: openjdk:17
    ports:
      - "8080:8080"
    volumes:
      - ./deploy/:/deploy/
    environment:
      TZ: "Asia/Seoul"
    command:
      - "/bin/sh"
      - "-c"
      - |
        java \
        -Xms2048m \
        -Xmx2048m \
        -Dserver.port=8080 \
        -Dspring.profiles.active=dev \
        -jar /deploy/demo-api-0.0.1-SNAPSHOT.jar
  external-api:
    image: openjdk:17
    ports:
      - "8081:8081"
    volumes:
      - ./deploy/:/deploy/
    environment:
      TZ: "Asia/Seoul"
    command:
      - "/bin/sh"
      - "-c"
      - |
        java \
        -Xms2048m \
        -Xmx2048m \
        -Dserver.port=8081 \
        -Dspring.profiles.active=dev \
        -jar /deploy/external-api-0.0.1-SNAPSHOT.jar
  external-api-nginx:
    image: nginx:1.17.9
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "80:80"
    volumes:
      - ./config/:/config/
      - ./config/nginx.conf:/etc/nginx/nginx.conf
